name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sbt_version: 1.2.8
            test_groups: 'basic/*'
          - sbt_version: 1.3.13
            test_groups: 'basic/* 1.3+/*'
          - sbt_version: 1.4.0
            test_groups: 'basic/* 1.3+/*'
          - sbt_version: 1.8.3
            test_groups: 'basic/* 1.3+/*'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Test
        run: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "^^${{ matrix.sbt_version }}" "scripted ${{ matrix.test_groups }}"
