name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ created ]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sbt_version: 1.3.13
          - sbt_version: 1.4.0
          - sbt_version: 1.8.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Test
        run: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "^^${{ matrix.sbt_version }}" "scripted basic/*"

  release:
    needs: [ test ]
    if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  update-version-number:
    needs: [ release ]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Update version number in example project
        run: |
          echo 'addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "${{ github.ref_name }}")' > example/project/plugins.sbt
      - uses: EndBug/add-and-commit@v9
        with:
          message: '[skip ci] Update plugin version in example repo'
